/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apisv1alpha1 "sigs.k8s.io/multi-network/apis/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PodNetworkLister helps list PodNetworks.
// All objects returned here must be treated as read-only.
type PodNetworkLister interface {
	// List lists all PodNetworks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1alpha1.PodNetwork, err error)
	// Get retrieves the PodNetwork from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisv1alpha1.PodNetwork, error)
	PodNetworkListerExpansion
}

// podNetworkLister implements the PodNetworkLister interface.
type podNetworkLister struct {
	listers.ResourceIndexer[*apisv1alpha1.PodNetwork]
}

// NewPodNetworkLister returns a new PodNetworkLister.
func NewPodNetworkLister(indexer cache.Indexer) PodNetworkLister {
	return &podNetworkLister{listers.New[*apisv1alpha1.PodNetwork](indexer, apisv1alpha1.Resource("podnetwork"))}
}
