---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - multinetwork.networking.k8s.io
  resources:
  - podnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multinetwork.networking.k8s.io
  resources:
  - podnetworks/finalizers
  verbs:
  - update
- apiGroups:
  - multinetwork.networking.k8s.io
  resources:
  - podnetworks/status
  verbs:
  - get
  - patch
  - update
